Update ember-composability-tools to latest version
miguelcobain/ember-leaflet pull request #696
Opened 2024-09-25 12:40 UTC by VladMoglan-eaton

Following the release of version 2.0.0 that fixes [a cyber-security license risk](https://github.com/miguelcobain/ember-composability-tools/issues/61) I would like to request the update of ember-composability-tools. I tested the update using `ember test --server`.

2024-10-03 11:50 UTC, VladMoglan-eaton commented
@miguelcobain Could this please be merged?

2026-06-28 22:31 UTC, jelhan requested changes
Thanks a lot for your contribution. This addon has been adopted by community. I'm happy to support you getting the PR in the next version of you are still motivated to get ot over the finish line.

2026-06-28 22:31 UTC, jelhan commented on package.json
> +    "ember-composability-tools": "^2.0.0",
Please widen support range to include v2 but don't drop support for v1. That will ease upgrades for everyone depending on more than one addon having a transitive dependency to ember-compatibility-tools. Or is there a strong reason why we cannot support both versions in parallel?

2026-07-26 17:52 UTC, jelhan commented
Done in #737.

I decided that it's not worth maintaining compatibility with two majors in this case. ember-compatibility-tools is only used 2-3 other actively maintained addons. Collisions are not that likely. And the majors should be API-compatible with each other's allowing every consumer to resolve conflicts via pnpm overrides or similar techniques.

2026-07-26 17:52 UTC, closed without merging